export function isNative(value: any): boolean;
export function isObject(value: any): boolean;
export function isArray(value: any): boolean;
export function isFunction(value: any): boolean;
export function isString(value: any): boolean;
export function isNumber(value: any): boolean;
export function isFloat(value: any): boolean;
export function isUndefined(value: any): boolean;
export function isNull(value: any): boolean;
export function isFalsy(value: any): boolean;
export function isElement(elem: any): boolean;
export function isAbsoluteURL(url: any): boolean;
export function isCssVarSupport(): boolean;
export const isNaN: (number: unknown) => boolean;
